Feature/postgres secrets
management-of-dispute-resolution/dispute_resolution pull request #10
Opened 2023-10-07 08:15 UTC by OlgaSHp

1.Добавила библиотеку dotenv
2.Удалила из pre-commit проверки на наличие docstring и длину строки в файле settings.py. В этом файле это вроде не требуется проверять.
3.Добавила файл .env.example

2023-10-07 11:22 UTC, alekseikoznov requested changes

2023-10-07 11:22 UTC, alekseikoznov commented on src/config/settings.py
>          "NAME": os.getenv("POSTGRES_DB", "django"),
Убери здесь параметры по умолчанию для всех значений

2023-10-07 11:22 UTC, alekseikoznov commented on .env.example
> +DB_PORT=mydbport_if_not_standard
давай сделаем DB_PORT=5432

2023-10-08 09:27 UTC, OlgaSHp commented on src/config/settings.py
>          "NAME": os.getenv("POSTGRES_DB", "django"),
Убрала

2023-10-08 09:27 UTC, OlgaSHp commented on .env.example
> +DB_PORT=mydbport_if_not_standard
поменяла

2023-10-08 15:55 UTC, alekseikoznov approved these changes

2023-10-08 15:55 UTC, merged