Feature/comments
management-of-dispute-resolution/dispute_resolution pull request #150
Opened 2023-11-24 12:35 UTC by zxcmax

Добавлена полная информация о пользователе в комментариях

В комментарии сделан такой же вывод информации о файле, как и в Dispute

2023-11-24 16:24 UTC, alekseikoznov requested changes

2023-11-24 16:24 UTC, alekseikoznov commented on src/disputes/models.py
> -        validators=[MinLengthValidator(MIN_LENGTH), text_validator()],
Я видимо забыл это в tg написать, когда вы обсуждали 
Это условие тестировщики поставили, так что давайте уже оставим такие граничные условия, хотя они немного нереалистичные)

2023-11-24 16:25 UTC, alekseikoznov commented on src/disputes/models.py
> -        validators=[MinLengthValidator(MIN_LENGTH), text_validator()],
Нужно вернуть валидатор))

2023-11-24 18:29 UTC, zxcmax commented on src/disputes/models.py
> -        validators=[MinLengthValidator(MIN_LENGTH), text_validator()],
Да так не должно быть. Не всегда же тестировщики правы

2023-11-25 12:47 UTC, alekseikoznov approved these changes

2023-11-25 12:47 UTC, merged