Feature/token fixing
management-of-dispute-resolution/dispute_resolution pull request #45
Opened 2023-10-20 13:24 UTC by OlgaSHp

Кроме настроек по djoser внесла @property
    def is_author(self) и 
 @property
    def is_opponent(self):

в модель CustomUser. При отправке запроса GET на получение все диспутов, выдавало ошибку, что нет таких аттрибутов в моделе, а в пермишеннах у нас проверяется.

Сейчас список диспутов приходит нормально.

2023-10-21 09:51 UTC, alekseikoznov requested changes
Я там перед отправкой на ревью внес какие-то изменения, связанные с авторизацией
Из-за них конфликты возникают, их спулить нужно

2023-10-21 09:51 UTC, alekseikoznov commented on src/users/models.py
> +        return self.role == 'opponent'
У нас же нет такой роли 'opponent', только user и mediator

2023-10-21 09:51 UTC, alekseikoznov commented on src/users/models.py
> +        return self.role == 'user'
Тут идет проверка на автора, но проверяется является ли роль пользователя 'user'

2023-10-24 14:26 UTC, zxcmax commented on src/users/models.py
> +        return self.role == 'user'
Мы же не сможем никаким образом проверить, что пользователь - автор или оппонент в диспуте. Эти property не нужны

2023-10-28 13:58 UTC, closed without merging