The opponent cannot be the creator
management-of-dispute-resolution/dispute_resolution pull request #69
Opened 2023-10-27 15:58 UTC by zxcmax

Теперь нельзя добавить себя в оппоненты через api. Через модель не разобрался как сделать из-за того что типы полей разные. Вроде как вообще не возможно сделать так, чтобы через админку нельзя было добавлять себя в оппоненты

2023-10-28 14:22 UTC, alekseikoznov requested changes

2023-10-28 14:22 UTC, alekseikoznov commented on src/api/views.py
> +        opponent_ids = request.data.get('opponent', [])
Значения id оппонентов могут приходить в формате str, если их добавлять через formdata
Нужно список opponent_ids переделать в int, например с помощью map()

2023-10-28 20:13 UTC, zxcmax commented
Готово. Сделал декоратор, чтобы не было дублирования кода. Добавил проверку и к PATCH запросу.

2023-10-29 09:32 UTC, alekseikoznov commented
Молодец! 
Круто сделал с декоратором)

2023-10-29 09:32 UTC, alekseikoznov approved these changes

2023-10-29 09:32 UTC, merged