Feature/pagination
management-of-dispute-resolution/dispute_resolution pull request #97
Opened 2023-11-09 16:52 UTC by Esperansa08

https://github.com/management-of-dispute-resolution/dispute_resolution_backend/issues/92

1. Настроила пагинацию
2. При указании значения параметра page_size меняется количество выдаваемых обращений на странице.

2023-11-09 18:43 UTC, alekseikoznov requested changes
В плане функционала - супер

У нас на проекте есть pre-commit
Это штука с линтерами, которая при коммите автоматически проверяет код
Она вообще должна была установиться автоматически, но видимо что-то пошло не так, потому что я вижу, что у тебя есть по pep8 недочеты
Надо установить pre-commit: pre-commit install
Проверить, что нормально установилось: pre-commit --version

Далее при каждом коммите будет происходить автоматическая проверка линтером, а так же будет происходить автоматическое приведение к единому стилю

2023-11-10 15:23 UTC, Esperansa08 commented
настроила  pre-commit. 
добавила докстринг классу пагинации

2023-11-10 15:52 UTC, alekseikoznov approved these changes

2023-11-10 15:52 UTC, alekseikoznov commented
Отлично!

2023-11-10 15:53 UTC, merged